# Generated by Django 5.1 on 2024-09-12 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qb_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRoleProfile',
            new_name='UserProfileDetails',
        ),
    ]
