# Generated by Django 5.1 on 2024-09-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb_order', '0002_userorder_userorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='item_image_url',
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='is_veg',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='item_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
