# Generated by Django 5.1 on 2024-09-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb_order', '0004_fooditem_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorderitem',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
