# Generated by Django 5.1 on 2024-10-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb_order', '0005_userorderitem_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='item_image_url',
            field=models.URLField(default='https://example.com/default-image.jpg'),
        ),
    ]
