# Generated by Django 5.1 on 2024-10-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb_order', '0006_fooditem_item_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorderitem',
            name='count',
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='item_image_url',
            field=models.URLField(),
        ),
    ]
