# Generated by Django 5.1 on 2024-10-01 06:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb_order', '0007_remove_userorderitem_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='order_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
