# Generated by Django 5.1 on 2024-10-01 06:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb_order', '0008_alter_userorder_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='user_id',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
