# Generated by Django 5.1 on 2024-10-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qb_order', '0009_alter_userorder_order_id_alter_userorder_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userorderitem',
            old_name='order_id',
            new_name='order',
        ),
    ]
